apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: banner-gitops
spec:
  backgroundColor: red
  color: '#fff'
  location: BannerTop
  text: WARNING: Cluster operated by GitOps
