apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console-banner
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: config-def/console-banner
    repoURL: https://github.com/gitops-jml/gitops-with-argocd.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  
