apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-catalog
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cp4i
  source:
    repoURL: 'https://github.com/gitops-jml/gitops-with-argocd.git'
    path: apps-def/CP4I/ibm-catalog
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
