apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-simplenodejs-dev
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: simplenodejs-dev
  project: default
  source:
    path: apps-def/simplenodejs/dev
    repoURL: https://github.com/gitops-jml/gitops-with-argocd.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
