apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simplenodeapp
  labels:
    app: simplenodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplenodeapp
  template:
    metadata:
      labels:
        app: simplenodeapp
    spec:
      containers:
      - name: simplenodeapp
        image: TBD
        ports:
        - containerPort: 8080