apiVersion: v1
kind: Service
metadata:
  name: simplenodeapp
  namespace: simplenodeapp
spec:
  type: nodePort
  ports:
  - port: 80           
    targetPort: 8080   
  selector:                
    app: simplenodeapp   
