  
# apply a common label on every objects
#======================================
commonLabels:
  env: prod

# same namespace for all objects
#===============================
namespace: simplenodejs-prod

#add a common suffix to objects
#==============================
nameSuffix: "-prod"

# change route target (due to common suffix)
#=============================================================================
patches:
  - patch: |-
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: simplenodejs
      spec:
        port:
          targetPort: 8080
        to:
          kind: Service
          name: simplenodejs-prod

# patch route
#==================
patches:
  - patch: |-
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: simplenodejs
      spec:
        to:
          kind: Service
          name: simplenodejs-prod



resources:
- ../base
- config-map.yaml

