apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console-link
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: config-def/console
    repoURL: https://github.com/gitops-jml/gitops
    targetRevision: HEAD
