# apply a common label on every objects
#======================================
commonLabels:
  env: dev

#add a common suffix to objects
nameSuffix: "-dev"

# create a config map
#====================
configMapGenerator:
- name: env-cm
  literals:
  - ENV=DEV
# patch the base deployment manifest to initialize the env from the config map
#=============================================================================
patches: 
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: simplenodeapp
      spec:
        template:
          spec:
            containers:
              - name: simplenodeapp
                env:
                  - name: ENV
                    valueFrom:
                      configMapKeyRef:
                        name: env-cm
                        key: ENV


resources:
- ../base

