  
# apply a common label on every objects
#======================================
commonLabels:
  env: dev

# same namespace for all objects
#===============================
namespace: simplenodejs-dev

#add a common suffix to objects
#==============================
nameSuffix: "-dev"

# change route target (due to common suffix)
#=============================================================================
patches:
  - patch: |-
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: simplenodejs
      spec:
        port:
          targetPort: 8080
        to:
          kind: Service
          name: simplenodejs-dev

# select config map
#=============================================================================
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: simplenodeapp
      spec:
        template:
          spec:
            containers:
            - name: simplenodeapp
              env:
                - name: ENV
                  valueFrom:
                    configMapKeyRef:
                    name: env-cm-dev
                    key: ENV
resources:
- ../base

