commonLabels:
  env: dev
configMapGenerator:
- name: env-cm
  literals:
  - ENV=DEV
patches: 
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: simplenodeapp
      spec:
        template:
          spec:
            containers:
              - name: simplenodeapp
                env:
                  - name: ENV
                    valueFrom:
                      configMapKeyRef:
                        name: env-cm
                        key: ENV
resources:
- ../base
- route.yaml
